### ISSUE TITLE
android 4.4  nativeOnDraw failed;

### ISSUE THREAD

**Issue by ant-ia** [madappstechnologies/MarkdownView-Android#10]
Hi,

I have a problem on devices with Android 4.4 (kitkat)

This is the error: ` nativeOnDraw failed; clearing to background color`

Practically the markdownview overwrites and also hides the toolbar.

I also tried it with: `markdown.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

but it does not solve the problem.

Tips?
Thank you

**Comment by mukeshsolanki** [comment]
Can you please paste the full stack trace and if possible past the code you are trying to execute

**Comment by ant-ia** [comment]
Hello,
I solved this problem by simply using the LinearLayout instead of RelativeLayout as a parent of markdownview.

**Comment by mukeshsolanki** [comment]
hmmm thats strange that should not have been the case. Anyways closing the issue
