### ISSUE TITLE
Handle click of link. Not call shouldOverrideUrlLoading()

### ISSUE THREAD

**Issue by alexei28** [madappstechnologies/MarkdownView-Android#12]
My code:

`public class MarkdownViewMukeshActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.markdown_view_mukesh_activity);

        MarkdownView markdownViewMukesh = (MarkdownView) findViewById(R.id.markdownView_Mukesh);
        markdownViewMukesh.setWebViewClient(new MyWebViewClient());
        markdownViewMukesh.loadMarkdownFromAssets("my_custom.md");
    }
}`

My WebClient class:

`

public class MyWebViewClient extends WebViewClient {

    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if (url.contains("command:")) {
             // do some custom handle
            }
            return true;
        } else {
            return false;
        }
    }`

My markdown_view_mukesh_activity.xml:

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.mukesh.MarkdownView
        android:id="@+id/markdownView_Mukesh"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>`

File my_custom.md success show. But when I click some link - NOT call method **shouldOverrideUrlLoading()**. Why?

**Comment by mukeshsolanki** [comment]
you can simply set a webclient and over the control. Thats not how thing would work.
