### ISSUE TITLE
Can apply CSS style?

### ISSUE THREAD

**Issue by alexei28** [madappstechnologies/MarkdownView-Android#13]
My code:

`public class MarkdownViewMukeshActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.markdown_view_mukesh_activity);

        MarkdownView markdownViewMukesh = (MarkdownView) findViewById(R.id.markdownView_Mukesh);
         markdownViewMukesh.loadMarkdownFromAssets("my_file.md");
    }
}`

OK. It's work.
The question is: Can I apply also CSS style to markdown file?

**Comment by mukeshsolanki** [comment]
md files are not meant to have css styling

**Comment by pravingaikwad07** [comment]
any update ? https://github.com/falnatsheh/MarkdownView something like this /?
